/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
	extend: 'Ext.panel.Panel',

	height: 480,
	layout: {
		type: 'border'
	},
	closable: false,
	collapsed: false,

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [{
				xtype: 'panel',
				region: 'west',
				split: true,
				width: 150,
				layout: {
					type: 'accordion'
				},
				items: [{
					xtype: 'panel',
					collapsed: false,
					layout: {
						type: 'vbox'
					},
					title: 'Estadisticas',
					items: [{
						xtype: 'label',
						/*text: 'Rendimiento anual',*/
						html: '<a>Denuncias por meses</a>',
						listeners: {
							click: {
								element: 'el',
								//bind to the underlying el property on the panel
								fn: function() {
									var win = Ext.create('MyApp.view.MyWindow');
									win.setVisible(true);
									win.show();

								}
							}
						}
					},
					{
						xtype: 'label',
						/*text: 'Sueldos - Gerentes',*/
						html: '<a>Ranking </a>',
						listeners: {
							click: {
								element: 'el',
								//bind to the underlying el property on the panel
								fn: function() {
									var msgCt = Ext.query("#msg-div");
									console.log(msgCt);
									if (msgCt[0] == null) {
										msgCt[0] = Ext.DomHelper.insertFirst(document.body, {
											id: 'msg-div'
										}, true);
									}
									var m = Ext.DomHelper.append(msgCt[0], '<div class="msg"><h3>Pendiente</h3><p>No disponible en esta Version</p></div>', true); /*msgCt.hide();*/
									m.slideIn('t').ghost("t", {
										delay: 2000,
										remove: true
									});
								}
							}
						}
					}]
				},
				{
					xtype: 'panel',
					collapsed: true,
					title: 'Sitios relacionados'
				},
				{
					xtype: 'panel',
					collapsed: true,
					title: 'Conozcanos'
				}]
			},
			{
				xtype: 'tabpanel',
				region: 'center',
				disabled: false,
				draggable: false,
				floating: false,
				bodyBorder: false,
				overlapHeader: false,
				activeTab: 0,
				items: [
				
								
				{
					 xtype: 'gmappanel',
					 title:'Mapa',
					 id:'mapa',
					 tbar: [{
						text: 'Refrescar',
						id:'refrescarMapa',
						name:'refrescarMapa'
						
					}],
					 mapOptions:
					 {
						 zoom: 12,
						 mapTypeId: google.maps.MapTypeId.ROADMAP
						 },
                    center: {
                        geoCodeAddr: ' lord cochrane 20, Santiago,Chile'
                    },
                    markers: [
					/*{
                        lat: -33.4492362,
                        lng: -70.654778,
                        title: 'PROBLEMA\n Haga click para ver',
                        listeners: {
							mouseup:function(e){
								window.win.close();
							},
                            mousedown: function(e){
                              		window.win = Ext.create('MyApp.view.MyWindowImage',{height: 216,width: 249, imagen:'images/p1.jpg'});
									win.setVisible(true);
									win.show();
                            }
                        }
                    }
					,{
                       lat: -33.4492372,
                        lng: -70.654778,
                        title: 'Otra'
                    }*/
					]
				},
				{
					xtype: 'panel',
					tbar: [{
						text: 'Refrescar',
						handler: function() {
							store1.loadData(generateData(12));
						}
					}],
					layout: {
						type: 'border'
					},
					title: 'Cruce anual',
					items: [{
						id: 'chartCmp2',
						xtype: 'chart',
						style: 'background:#fff',
						theme: 'Category6',
						insetPadding: 20,
						animate: true,
						store: store1,
						legend: {
							position: 'right'
						},
						axes: [{
							type: 'Radial',
							position: 'radial',
							label: {
								display: true
							}
						}],
						series: [{
							showInLegend: true,
							type: 'radar',
							xField: 'name',
							yField: 'solucionados',
							style: {
								opacity: 0.4
							}
						},
						{
							showInLegend: true,
							type: 'radar',
							xField: 'name',
							yField: 'pendientes',
							style: {
								opacity: 0.4
							}
						}]
					}]
				},
				{
					xtype: 'panel',
					layout: {
						type: 'border'
					},
					tbar: [{
						text: 'Refrescar',
						handler: function() {
							store1.loadData(generateData(12));
						}
					}],
					title: 'Problemas presentados vs resueltos',
					items: [{
						xtype: 'chart',
						style: 'background:#fff',
						animate: true,
						store: store1,
						shadow: true,
						theme: 'Category1',
						legend: {
							position: 'right'
						},
						axes: [{
							type: 'Numeric',
							minimum: 0,
							position: 'left',
							fields: ['solucionados', 'pendientes'],
							title: '$ x 1000',
							minorTickSteps: 1,
							grid: {
								odd: {
									opacity: 0.8,
									fill: '#ddd',
									stroke: '#bbb',
									'stroke-width': 0.5
								}
							}
						},
						{
							type: 'Category',
							position: 'bottom',
							fields: ['name'],
							title: 'Meses'
						}],
						series: [{
							type: 'line',
							highlight: {
								size: 7,
								radius: 7
							},
							axis: 'left',
							xField: 'name',
							yField: 'solucionados',
							markerConfig: {
								type: 'cross',
								size: 4,
								radius: 4,
								'stroke-width': 0
							}
						},
						{
							type: 'line',
							highlight: {
								size: 7,
								radius: 7
							},
							axis: 'left',
							smooth: true,
							xField: 'name',
							yField: 'pendientes',
							fill: true,
							markerConfig: {
								type: 'circle',
								size: 4,
								radius: 4,
								'stroke-width': 0
							}
						}
						]
					}]
				}
				]
			}]
		});

		me.callParent(arguments);
	}

});