/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
	extend: 'Ext.window.Window',

	height: 416,
	width: 749,
	constrain: true,
	layout: {
		type: 'border'
	},
	modal: true,
	maximizable: true,
	title: 'Denuncias por mes',

	initComponent: function()
	{
		var me = this;

		Ext.applyIf(me, {
			items: [
			{
				xtype: 'panel',
				region: 'center',
				layout: {
					type: 'border'
				},
				collapsed: false,
				collapsible: true,

				items: [
				{
					id: 'chartCmpW',
					xtype: 'chart',
					style: 'background:#fff',
					region: 'center',
					animate: true,
					shadow: true,
					store: window.store1,
					axes: [
					{
						type: 'Numeric',
						position: 'left',
						fields: ['data1'],
						label: {
							renderer: Ext.util.Format.numberRenderer('0,0')
						},
						title: '$ x 1000',
						grid: true,
						minimum: 0
					},
					{
						type: 'Category',
						position: 'bottom',
						fields: ['name'],
						title: 'Meses'
					}],
					series: [
					{
						type: 'column',
						axis: 'left',
						highlight: true,
						tips: {
							trackMouse: true,
							width: 140,
							height: 28,
							renderer: function(storeItem, item)
							{
								this.setTitle(storeItem.get('name') + ': ' + storeItem.get('data1') + ' $');
							}
						},
						label: {
							display: 'insideEnd',
							'text-anchor': 'middle',
							field: 'data1',
							renderer: Ext.util.Format.numberRenderer('0'),
							orientation: 'vertical',
							color: '#333'
						},
						xField: 'name',
						yField: 'data1'
					}] }

				]
			}]
		});

		me.callParent(arguments);
	}

});